"""Add AlertChannel

Revision ID: 340b50453018
Revises: b45f1f4c004e
Create Date: 2026-07-25 15:29:46.666387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340b50453018'
down_revision: Union[str, Sequence[str], None] = 'b45f1f4c004e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_channels_id'), 'alert_channels', ['id'], unique=False)
    op.add_column('gateway_logs', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    op.drop_column('gateway_logs', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_logs', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('gateway_logs', 'time_stamp')
    op.drop_index(op.f('ix_alert_channels_id'), table_name='alert_channels')
    op.drop_table('alert_channels')
    # ### end Alembic commands ###
