"""Add GatewayLog

Revision ID: 377c5b21546a
Revises: 43b867b2c329
Create Date: 2026-07-23 02:06:02.839213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377c5b21546a'
down_revision: Union[str, Sequence[str], None] = '43b867b2c329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('provider_used', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('threat_classification', sa.String(), nullable=True),
    sa.Column('action_taken', sa.Enum('ALLOWED', 'BLOCKED', 'FAILED', name='actiontaken'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('token_usage_prompt', sa.Integer(), nullable=True),
    sa.Column('token_usage_completion', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_logs_client_id'), 'gateway_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_gateway_logs_id'), 'gateway_logs', ['id'], unique=False)
    op.create_index(op.f('ix_gateway_logs_request_id'), 'gateway_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_logs_request_id'), table_name='gateway_logs')
    op.drop_index(op.f('ix_gateway_logs_id'), table_name='gateway_logs')
    op.drop_index(op.f('ix_gateway_logs_client_id'), table_name='gateway_logs')
    op.drop_table('gateway_logs')
    # ### end Alembic commands ###
